import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // pilih sesuai kebutuhan
})

export const metadata = {
  title: 'Your App',
  description: 'Generated by Next.js',
}


export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
    >
      <body className={poppins.className}>
        {children}
      </body>
    </html>
  );
}
